### ISSUE TITLE
Jupyter notebook

### ISSUE THREAD

**Issue by t-kimber** [volkamerlab/klifs_utils#9]
Dear klifs_utils devs,

Should jupyter notebook exists in the env.yml file ?

**Comment by dominiquesydow** [comment]
Hi @t-kimber, 

Good question!

Since the repo contains Jupyter notebooks to play around with (e.g. as a quick start), I thought it makes sense to include `jupyterlab` to the `env.yaml` file. 

However, the actual package does not need `jupyterlab`, from that point of view it should not be included.

@jaimergp - is it bad practice to include packages in the `env.yaml` that are not used by the package itself but in the context of the full repo?

**Comment by jaimergp** [comment]
I would suggest including such a dependency in the environment file. 

Packaging the repo for  `conda` would be a different thing and even in that case it could be argued how `jupyter` would be required. So by any means, yes, include it!
